/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AIMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProjectStage = IDL.Variant({
  'video' : IDL.Null,
  'idea' : IDL.Null,
  'script' : IDL.Null,
  'published' : IDL.Null,
  'visuals' : IDL.Null,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'scriptContent' : IDL.Text,
  'createdAt' : Time,
  'designNotes' : IDL.Text,
  'videoNotes' : IDL.Text,
  'updatedAt' : Time,
  'stage' : ProjectStage,
  'aiHistory' : IDL.Vec(AIMessage),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAIMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminBanUser' : IDL.Func([IDL.Principal], [], []),
  'adminIsBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAIHistory' : IDL.Func([IDL.Text], [IDL.Vec(AIMessage)], ['query']),
  'getBanTimestamp' : IDL.Func([], [Time], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isBanned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateProjectStage' : IDL.Func([IDL.Text, ProjectStage], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AIMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProjectStage = IDL.Variant({
    'video' : IDL.Null,
    'idea' : IDL.Null,
    'script' : IDL.Null,
    'published' : IDL.Null,
    'visuals' : IDL.Null,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'scriptContent' : IDL.Text,
    'createdAt' : Time,
    'designNotes' : IDL.Text,
    'videoNotes' : IDL.Text,
    'updatedAt' : Time,
    'stage' : ProjectStage,
    'aiHistory' : IDL.Vec(AIMessage),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAIMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminBanUser' : IDL.Func([IDL.Principal], [], []),
    'adminIsBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'adminUnbanUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteProject' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAIHistory' : IDL.Func([IDL.Text], [IDL.Vec(AIMessage)], ['query']),
    'getBanTimestamp' : IDL.Func([], [Time], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isBanned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateProjectStage' : IDL.Func([IDL.Text, ProjectStage], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };